### ISSUE TITLE
Convenient API to use it from python is strongly needed.

### ISSUE THREAD

**Issue by KOLANICH** [rocky/python-xasm#1]

**Comment by rocky** [comment]
Feef free to submit a PR. You are probably in a better position to know what you strongly need than I. ;-)

**Comment by KOLANICH** [comment]
>You are probably in a better position to know what you strongly need than I. ;-)

In fact I don't need it anymore (I have figured out that the thing I wanna do is impossible to do by messing with bytecode alone). But I guess other users may need.

>Feel free to submit a PR.

It's your lib, anyway. :)

**Comment by rocky** [comment]
> It's your lib, anyway.

Yes, and for me, for now, this suits my needs. I offered it to the public should it be helpful for others, and to allow the possibility that others might contribute to make it better for everyone. 

However if in the future I find the need for whatever you think was strongly needed, then I would add that, and your request is superfluous. 

Even though your request wasn't motivated by altruism but to get help from someone else to assist you in whatever you were doing, there may be someone else who feels the desire to do this, even though you don't need it any more. So we can leave this open.

**Comment by rocky** [comment]
closing for lack of apparent interest/movement.
