### ISSUE TITLE
Output from xdis doesn't work when assembling with xasm

### ISSUE THREAD

**Issue by Svenskithesource** [rocky/python-xasm#14]
Hello,

I ran this command:
`pydisasm --format xasm myfile.pyc > test.pyasm`

then the next command:
`py run.py` (I made this file because of some weirdness with my python versions, just assume it executes the same way as `pyc-xasm test.pyasm`)

The problem is with the jumps:
`
RuntimeError: Label (to 16) not found.
I know about {      POP_JUMP_IF_FALSE   (to 16),       JUMP_ABSOLUTE    (to 16)}. Instruction 24:
      POP_JUMP_IF_FALSE (to 16)`

The bytecode looks like this
`POP_JUMP_IF_FALSE (to 16)`

For some reason it thinks `(to 16)` is a label, while it's an offset. In your HOW-TO-USE.rst you specify that offsets can just be written like this: `POP_JUMP_IF_FALSE 16`

I could just make a regex and replace it like that to make it work but that feels a bit hacky. Is there any proper solution?

**Comment by rocky** [comment]
Attach a small bytecode (`.pyc`) file that exhibits the problem, and I'll look at when I get a chance.

**Comment by Svenskithesource** [comment]
Attached as a zip since Github doesn't allowe pyc file
[testing.zip](https://github.com/rocky/python-xasm/files/8191489/testing.zip)
s

**Comment by rocky** [comment]
I am not seeing a problem: 

```
$ pydisasm -F xasm testing.pyc | tee > testing.pyasm
# pydisasm version 6.0.4.dev0
# Python bytecode 3.9.0 (3425)
# Disassembled from Python 3.7.12 (default, Sep 21 2021, 05:11:53)
# [GCC 9.3.0]
# Timestamp in code: 1646514898 (2022-03-05 16:14:58)
# Source code size mod 2**32: 77 bytes

# Method Name:       <module>
# Filename:          testing.py
# Argument count:    0
# Position-only argument count: 0
# Keyword-only arguments: 0
# Number of locals:  0
# Stack size:        2
# Flags:             0x00000040 (NOFREE)
# First Line:        1
# Constants:
#    0: 'Hello'
#    1: 1
#    2: 'cool'
#    3: 'impossible'
#    4: None
# Names:
#    0: print
  1:
            LOAD_NAME            0 (print)
            LOAD_CONST           0 ('Hello')
            CALL_FUNCTION        1
            POP_TOP

  2:
            LOAD_CONST           1 (1)
            LOAD_CONST           1 (1)
            COMPARE_OP           2 (==)
            POP_JUMP_IF_FALSE    L26 (to 26)

  3:
            LOAD_NAME            0 (print)
            LOAD_CONST           2 ('cool')
            CALL_FUNCTION        1
            POP_TOP
            JUMP_FORWARD         L34 (to 34)

L26:
   5:
            LOAD_NAME            0 (print)
            LOAD_CONST           3 ('impossible')
            CALL_FUNCTION        1
            POP_TOP
L34:
            LOAD_CONST           4 (None)
            RETURN_VALUE
$ pyc-xasm testing.pyasm
Wrote Python 3.9 bytecode file "testing.pyc"; 206 bytes.
$

```

**Comment by Svenskithesource** [comment]
Your pyasm file looks different to mine, let me double check I have the latest version.

**Comment by Svenskithesource** [comment]
Of course, my bad I was still on version 5.0.9. Sorry for the unnecessary issue.

**Comment by rocky** [comment]
Pro tip: when reporting bugs details are important. Like what you started out with, what you typed and what you got. 

Had I been as vague as you and just said - works for me, we'd still be puzzling this out which probably has more of an impact on you than me.

**Comment by Svenskithesource** [comment]
I'll keep this in mind for next time, thanks
