### ISSUE TITLE
Incorrect version check in `create_code`?

### ISSUE THREAD

**Issue by Andoryuuta** [rocky/python-xasm#2]
I'm not sure whether this is a bug, or intended functionality, but I figured I would post it anyway.

In [`xasm/assembly.py`'s `create_code` function](https://github.com/rocky/python-xasm/blob/master/xasm/assemble.py#L422-L428) it uses the assembler's bytecode version, instead of the current interpreter version, to determine whether `co_code` should be a bytes-like object or a str.
```python
if asm.opc.version >= 3.0:
    co_code = bytearray()
    for j in bcode:
        co_code.append(j)
    asm.code.co_code = bytes(co_code)
else:
    asm.code.co_code = ''.join([chr(j) for j in bcode])
```

In my specific case, I'm assembling Python 2.7 instructions from a Python 3.7 interpreter, and passing the resulting code object to uncompyle6, which expects a bytes-like `co_code`, so I have to convert it first:
```python
code = create_code(asm, [], [])

# HACK/FIX: xasm's `create_code` makes `co_code` a str on opcode version < 3,
# and uncompyle6 requires this to be bytes-like, so we convert it.
if sys.version_info > (3, 0, 0):
    code.co_code = bytes([ord(c) for c in code.co_code])

uncompyle6.main.decompile(version, code, sys.stdout)
```

If this is intended functionally, feel free to close the issue or tell me and I'll close it. :)

**Comment by rocky** [comment]
Dunno. Will look into this to see what's up when I get a chance.

**Comment by rocky** [comment]
Just had a chance to look at in more detail. 

> In xasm/assembly.py's create_code function it uses the assembler's bytecode version, instead of the current interpreter version, to determine whether co_code should be a bytes-like object or a str.

That is what I believe it should do. 

> ... `uncompyle6.main.decompile(version, code, sys.stdout) `

what is the value of `version`?

Unfortunately there isn't enough detail to determine if this is bug or if it is a misunderstanding of how things work or how to use the code. 

What would be helpful is a compilete example. To fix a bug, many times one needs to be able to reproduce it, and from the information here, that would require guessing, which I don't have the time nor interest to do.

**Comment by rocky** [comment]
Closing for lack of information/interest.
