### ISSUE TITLE
xdis version issues

### ISSUE THREAD

**Issue by winrg** [rocky/python-xasm#22]
The last few versions of xdis are fully incompatible with this package in a number of places. I spent about an hour futzing around, partially patching the package, and only got garbled outputs, even from direct disassemblies.

I see a lot of commits like, "make dependabot happy", on the requirements.txt. What is the last *tested* version of xdis that this project works with?

**Comment by rocky** [comment]
Use the latest xdis, even better use master from git and the master version of xasm and I think you'll be okay.
