### ISSUE TITLE
PEP 552 Header for Python >= 3.7

### ISSUE THREAD

**Issue by extremecoders-re** [rocky/python-xasm#3]
_.pyc_ files from Python versions 3.7 and above have a 16 byte header ([PEP 552](https://www.python.org/dev/peps/pep-0552/#id15)) as opposed to 12 bytes in Python 3.3-3.6.

The `write_pyc` file function doesn't take this into account.
https://github.com/rocky/python-xasm/blob/f88191b48b8279405382497ba2a5df9a210e76c1/xasm/write_pyc.py#L8-L26

**Comment by rocky** [comment]
Thanks for the detailed report. 

Want to put in a PR to fix?

**Comment by extremecoders-re** [comment]
In my local copy, I've fixed it with something like:

```
     if version > 3.2: 
         fp.write(pack('<I', 0)) # size mod 2**32 
         if version > 3.6: 
             fp.write(pack('<I', 0))
```

This works, although not semantically correct.

As according to the PEP, the second dword represents a bitfield (as opposed to timestamp) and the interpretation of the third and fourth dwords depends on this bitfield.

Detailed fix is possible but would make this a bit complicated. Would be eager to look at your bug fix. :).

**Comment by rocky** [comment]
Hey, thanks. I appreciate your sharing your local fix. We can leave this open in case somebody else wants to use your fix or address this more properly. I also added a sponsor button if people want to show support.
