### ISSUE TITLE
RuntimeError in pyc-xasm

### ISSUE THREAD

**Issue by QemuK** [rocky/python-xasm#7]
I want to compile a .pyasm file to .pyc via using pyc-xasm

This is my main.py

`print("Hello, world")`

I compiled this as main.pyc

And

`pydisasm main.pyc > main.pyasm`

Now I want to convert the file back

`pyc-xasm main.pyasm`

    

> RuntimeError: Don't understand operand ('Hello, expecting int or (..). Instruction 1: LOAD_CONST ('Hello,

**Comment by rocky** [comment]
Use the option `--format xasm` on the pydisam command.

**Comment by QemuK** [comment]
Did not help. I am sending you a file

[main.txt](https://github.com/rocky/python-xasm/files/6151079/main.txt)

**Comment by rocky** [comment]
Your file isn't in the proper format. Look at the README.rst to see the correct kind of format.

**Comment by QemuK** [comment]
It's not about the format. I changed it to .text to upload the file to github
